esphome:
  name: shop-garage-door
  friendly_name: Shop Garage Door

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key


ota:
  - platform: esphome
    password: !secret web_server_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door-Test"


captive_portal:
    
# Enable Web Server (optional, for testing)
web_server:
  port: 80


# Relay for controlling the garage door
switch:
  - platform: gpio
    pin: GPIO14
    id: garage_door_relay
    name: "Garage Door Relay"
    icon: "mdi:garage"
    on_turn_on:
      - delay: 1s  # Adjust the delay as needed (e.g., 1 second)
      - switch.turn_off: garage_door_relay

      
# Reed switch to detect door state
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: False
    name: "Garage Door Reed Switch"
    device_class: door
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms

# Optional status LED
status_led:
  pin:
    number: GPIO2
    inverted: true


